
  %load_ext autoreload : magic command de Jupyter de autoreload
  
  %autoreload 2 : recarga todo automáticamente(2)

In [145]:
%load_ext autoreload 
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [146]:
# PAQUETE LIBRERIAS ANALISIS DE DATOS y de SKLEARN
import pandas as pd
import numpy as np
import seaborn as sea
import matplotlib.pyplot as plt

import sys
sys.path.append('..')

from src.eda import reporte_calidad
from src.eda import clasificar_formato_fecha
from src.eda import validar_fechas
from src.eda import resolver_duplicados

## 1) FACT_MANTENIMIENTO

In [147]:
directory =  r'C:\Users\jbard\Desktop\Library\@CURSOS ACTUALES\@Data Analitycs\Python projects\Mineria-simulacion v2'
fact_mtto_PC= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PC_raw.csv')
fact_mtto_PN= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PN_raw.csv')
fact_mtto_PS= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PS_raw.csv')

#### 1) FACT_MANTENIMIENTO_PC

1era verificacion de calidad

In [148]:
from src.eda import reporte_calidad
reporte_calidad(fact_mtto_PC,nombre_df='fact_mtto_PC')

--- Resumen: fact_mtto_PC ---
Total filas: 2735
Filas duplicadas: 27 (0.99%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,repuesto_principal,str,0.009872,2684,51,1.86,7
1,orden_id,str,0.009872,2735,0,0.00,2708
2,parada_id,str,0.009872,2735,0,0.00,2708
3,fecha_apertura,str,0.009872,2735,0,0.00,1271
4,equipo_id,str,0.009872,2735,0,0.00,10
5,tipo_orden,str,0.009872,2735,0,0.00,2
6,horas_hombre,float64,0.009872,2735,0,0.00,306
7,num_tecnicos,int64,0.009872,2735,0,0.00,3
8,costo_repuestos_soles,float64,0.009872,2735,0,0.00,2233

VERIFICACION TIPOS DE FECHA QUE HAY EN LA COLUMNA 'FECHA_APERTURA'

In [149]:
tipos_fecha=pd.DataFrame(
    {
        'fecha_apertura': fact_mtto_PC['fecha_apertura'],
        'tipo_fecha': fact_mtto_PC['fecha_apertura'].apply(clasificar_formato_fecha)
    }
)
display(tipos_fecha.head(3))
tipos_de_fecha= tipos_fecha['tipo_fecha'].value_counts()
tipos_de_fecha

#Como no existen mas de otros formatos de fecha, por tanto podemos aplicar directamente la trasnformacion. Hay que tomar en cuenta que quiza haya mas de un formato de fecha en la columna, si ese fuera el caso esto generaria que tengamos hacer tranformacion independiente y un simple pd.to_datetime(df['columna']) no seria suficiente.
#LA SOLUCION sera crear una pipeline para cada escenario o por el contrario hacerlo manualmente para cada tipo_fecha diferente. EN ESTA OCASION EL PIPELINE DE LA VALIDACION DE FECHA YA ESTA REALIZADO DENTRO DE EDA.PY

  fecha_apertura tipo_fecha
0     2024-05-28        YMD
1     2027-08-24        YMD
2     2027-09-11        YMD

tipo_fecha
YMD    2735
Name: count, dtype: int64

In [150]:
validar_fechas(fact_mtto_PC,'fecha_apertura')

Verificación:
     fecha_original tipo_fecha
0        2024-05-28        YMD
1        2027-08-24        YMD
2        2027-09-11        YMD
3        2025-10-03        YMD
4        2024-06-06        YMD
...             ...        ...
2730     2024-03-20        YMD
2731     2026-11-24        YMD
2732     2025-03-24        YMD
2733     2026-09-06        YMD
2734     2027-09-23        YMD

[2735 rows x 2 columns]

Validación correcta.
Todas las fechas tienen un único formato.
Fecha convertida a datetime.

In [151]:

if fact_mtto_PN['repuesto_principal'].isnull().any():
    fact_mtto_PN['repuesto_principal'] = fact_mtto_PN['repuesto_principal'].fillna('indeterminado')# Partamos del escenario donde algunos repuestos se perdería el nombre, sin embargo los costos no, por tanto simplemente averiguariamos el nombre del repuesto y reemplazariamos luego. Si existen nulos iría por defecto bajo el nombre 'Indeterminado'

    print("Nulos encontrados y reemplazados por 'indeterminado'.")
else:
    print("No se encontraron nulos en 'repuesto_principal', no se aplica transformación.")

Nulos encontrados y reemplazados por 'indeterminado'.

#### 2) FACT_MANTENIMIENTO_PS

In [152]:
from src.eda import reporte_calidad
reporte_calidad(fact_mtto_PS,nombre_df='fact_mtto_PS')

--- Resumen: fact_mtto_PS ---
Total filas: 2422
Filas duplicadas: 23 (0.95%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,repuesto_principal,str,0.009496,2376,46,1.9,7
1,orden_id,str,0.009496,2422,0,0.0,2399
2,parada_id,str,0.009496,2422,0,0.0,2399
3,fecha_apertura,str,0.009496,2422,0,0.0,1204
4,equipo_id,str,0.009496,2422,0,0.0,10
5,tipo_orden,str,0.009496,2422,0,0.0,2
6,horas_hombre,float64,0.009496,2422,0,0.0,277
7,num_tecnicos,int64,0.009496,2422,0,0.0,3
8,costo_repuestos_soles,float64,0.009496,2422,0,0.0,1999

In [153]:

if fact_mtto_PS['repuesto_principal'].isnull().any():
    fact_mtto_PS['repuesto_principal'] = fact_mtto_PS['repuesto_principal'].fillna('indeterminado')# Partamos del escenario donde algunos repuestos se perdería el nombre, sin embargo los costos no, por tanto simplemente averiguariamos el nombre del repuesto y reemplazariamos luego. Si existen nulos iría por defecto bajo el nombre 'Indeterminado'

    print("Nulos encontrados en 'repuesto_principal' y reemplazados por 'indeterminado'.")
else:
    print("No se encontraron nulos en 'repuesto_principal', no se aplica transformación.")

Nulos encontrados en 'repuesto_principal' y reemplazados por 'indeterminado'.

In [154]:
tipos_fecha=pd.DataFrame(
    {
        'fecha_apertura': fact_mtto_PS['fecha_apertura'],
        'tipo_fecha': fact_mtto_PS['fecha_apertura'].apply(clasificar_formato_fecha)
    }
)
display(tipos_fecha.head(3))
tipos_de_fecha= tipos_fecha['tipo_fecha'].value_counts()
tipos_de_fecha

#Como no existen mas de otros formatos de fecha, por tanto podemos aplicar directamente la trasnformacion. Hay que tomar en cuenta que quiza haya mas de un formato de fecha en la columna, si ese fuera el caso esto generaria que tengamos hacer tranformacion independiente y un simple pd.to_datetime(df['columna']) no seria suficiente.
#LA SOLUCION sera crear una pipeline para cada escenario o por el contrario hacerlo manualmente para cada tipo_fecha diferente. EN ESTA OCASION EL PIPELINE DE LA VALIDACION DE FECHA YA ESTA REALIZADO DENTRO DE EDA.PY

  fecha_apertura tipo_fecha
0     2024-10-14        YMD
1     2025-06-24        YMD
2     2024-09-17        YMD

tipo_fecha
YMD    2422
Name: count, dtype: int64

In [155]:
validar_fechas(fact_mtto_PS,'fecha_apertura')

Verificación:
     fecha_original tipo_fecha
0        2024-10-14        YMD
1        2025-06-24        YMD
2        2024-09-17        YMD
3        2024-12-29        YMD
4        2027-01-31        YMD
...             ...        ...
2417     2027-11-15        YMD
2418     2026-08-01        YMD
2419     2026-03-28        YMD
2420     2027-01-30        YMD
2421     2027-06-27        YMD

[2422 rows x 2 columns]

Validación correcta.
Todas las fechas tienen un único formato.
Fecha convertida a datetime.

#### 3) FACT_MANTENIMIENTO_PN

In [156]:
from src.eda import reporte_calidad
reporte_calidad(fact_mtto_PN,nombre_df='fact_mtto_PN')

--- Resumen: fact_mtto_PN ---
Total filas: 2829
Filas duplicadas: 28 (0.99%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,orden_id,str,0.009897,2829,0,0.0,2801
1,parada_id,str,0.009897,2829,0,0.0,2801
2,equipo_id,str,0.009897,2829,0,0.0,10
3,fecha_apertura,str,0.009897,2829,0,0.0,1273
4,tipo_orden,str,0.009897,2829,0,0.0,2
5,horas_hombre,float64,0.009897,2829,0,0.0,299
6,num_tecnicos,int64,0.009897,2829,0,0.0,3
7,repuesto_principal,str,0.009897,2829,0,0.0,8
8,costo_repuestos_soles,float64,0.009897,2829,0,0.0,2310

In [157]:
# Descartado 1, no puedo depender de verificar cada una de las tablas si es que se detectaran duplicados, la solucion es diseñar un pipeline que me permita identificar que hacer en caso se detecten duplicados, cuando considerar duplicados y cuando no.... todo manejado dentro de una funcion que pueda reutilizar siempre que se detecten duplicados
fact_mtto_PN[fact_mtto_PN.duplicated()].sort_values('orden_id')

,orden_id,parada_id,equipo_id,fecha_apertura,tipo_orden,horas_hombre,num_tecnicos,repuesto_principal,costo_repuestos_soles
2316,OT-000214,PAR-000282,PN-EQ-01,2027-03-19,Preventiva,7.7,3,Faja/correa,1274.0
1856,OT-000312,PAR-000425,PN-EQ-02,2024-09-26,Correctiva,9.7,1,Rodamiento,1420.0
952,OT-000486,PAR-000648,PN-EQ-02,2027-02-21,Correctiva,19.4,1,Sello mecánico,5666.0
2278,OT-000631,PAR-000852,PN-EQ-03,2025-12-28,Preventiva,4.7,3,Rodamiento,1921.0
2092,OT-000705,PAR-000961,PN-EQ-03,2027-05-18,Preventiva,7.1,3,Revestimiento (liner),2316.0
2770,OT-000966,PAR-001282,PN-EQ-04,2026-05-06,Preventiva,6.2,3,Motor eléctrico,536.0
2081,OT-000996,PAR-001322,PN-EQ-04,2026-09-21,Correctiva,8.0,1,Motor eléctrico,186.0
1957,OT-001146,PAR-001506,PN-EQ-05,2024-05-31,Correctiva,19.4,2,Sensor/instrumento,7635.0
2181,OT-001197,PAR-001571,PN-EQ-05,2025-02-04,Correctiva,14.5,1,Sensor/instrumento,3544.0
2774,OT-001259,PAR-001650,PN-EQ-05,2025-10-11,Preventiva,6.6,3,Ninguno (solo mano de obra),2077.0
2453,OT-001294,PAR-001693,PN-EQ-05,2026-03-21,Correctiva,7.6,3,Sensor/instrumento,2014.0
2260,OT-001624,PAR-002126,PN-EQ-06,2026-06-04,Correctiva,1.6,2,Sensor/instrumento,3425.0
638,OT-001751,PAR-002299,PN-EQ-07,2024-07-01,Correctiva,5.1,2,Motor eléctrico,1878.0
2446,OT-001768,PAR-002318,PN-EQ-07,2024-10-05,Correctiva,10.0,2,Sensor/instrumento,793.0
1116,OT-001776,PAR-002329,PN-EQ-07,2024-12-05,Correctiva,2.7,1,Sensor/instrumento,2422.0
2286,OT-001901,PAR-002507,PN-EQ-07,2027-05-22,Correctiva,0.7,3,Revestimiento (liner),3453.0
2699,OT-001923,PAR-002543,PN-EQ-07,2027-11-24,Correctiva,12.0,2,Revestimiento (liner),740.0
1166,OT-001965,PAR-002598,PN-EQ-08,2024-08-03,Preventiva,8.3,3,Sensor/instrumento,1366.0
788,OT-001978,PAR-002616,PN-EQ-08,2024-10-25,Correctiva,13.2,3,Faja/correa,7538.0
1943,OT-002036,PAR-002691,PN-EQ-08,2025-08-27,Correctiva,19.2,1,Faja/correa,2068.0
336,OT-002108,PAR-002785,PN-EQ-08,2026-08-02,Correctiva,20.6,2,Sensor/instrumento,2342.0
1533,OT-002171,PAR-002864,PN-EQ-08,2027-07-17,Preventiva,7.3,3,Sensor/instrumento,218.0
2578,OT-002299,PAR-003034,PN-EQ-09,2025-07-12,Correctiva,0.5,3,Revestimiento (liner),1916.0
1684,OT-002308,PAR-003043,PN-EQ-09,2025-08-31,Correctiva,4.8,3,Rodamiento,5236.0
1611,OT-002403,PAR-003182,PN-EQ-09,2027-07-20,Correctiva,1.9,2,Faja/correa,3672.0
806,OT-002521,PAR-003337,PN-EQ-10,2025-01-17,Correctiva,4.6,3,Faja/correa,5337.0
399,OT-002705,PAR-003564,PN-EQ-10,2026-11-08,Correctiva,21.1,1,Sello mecánico,3935.0
2330,OT-002711,PAR-003571,PN-EQ-10,2026-11-27,Correctiva,7.3,1,Faja/correa,5546.0

In [158]:

if fact_mtto_PN['repuesto_principal'].isnull().any():
    fact_mtto_PN['repuesto_principal'] = fact_mtto_PN['repuesto_principal'].fillna('indeterminado')# Partamos del escenario donde algunos repuestos se perdería el nombre, sin embargo los costos no, por tanto simplemente averiguariamos el nombre del repuesto y reemplazariamos luego. Si existen nulos iría por defecto bajo el nombre 'Indeterminado'

    print("Nulos encontrados en 'repuesto_principal' y reemplazados por 'indeterminado'.")
else:
    print("No se encontraron nulos en 'repuesto_principal', no se aplica transformación.")

No se encontraron nulos en 'repuesto_principal', no se aplica transformación.

In [159]:
tipos_fecha=pd.DataFrame(
    {
        'fecha_apertura': fact_mtto_PN['fecha_apertura'],
        'tipo_fecha': fact_mtto_PN['fecha_apertura'].apply(clasificar_formato_fecha)
    }
)
display(tipos_fecha.head(3))
tipos_de_fecha= tipos_fecha['tipo_fecha'].value_counts()
tipos_de_fecha

#Como no existen mas de otros formatos de fecha, por tanto podemos aplicar directamente la trasnformacion. Hay que tomar en cuenta que quiza haya mas de un formato de fecha en la columna, si ese fuera el caso esto generaria que tengamos hacer tranformacion independiente y un simple pd.to_datetime(df['columna']) no seria suficiente.
#LA SOLUCION sera crear una pipeline para cada escenario o por el contrario hacerlo manualmente para cada tipo_fecha diferente. EN ESTA OCASION EL PIPELINE DE LA VALIDACION DE FECHA YA ESTA REALIZADO DENTRO DE EDA.PY

  fecha_apertura tipo_fecha
0     2024-09-23        YMD
1     2026-03-06        YMD
2     2027-09-29        YMD

tipo_fecha
YMD    2829
Name: count, dtype: int64

In [160]:
reporte_calidad(fact_mtto_PN)

--- Resumen: DataFrame ---
Total filas: 2829
Filas duplicadas: 28 (0.99%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,orden_id,str,0.009897,2829,0,0.0,2801
1,parada_id,str,0.009897,2829,0,0.0,2801
2,equipo_id,str,0.009897,2829,0,0.0,10
3,fecha_apertura,str,0.009897,2829,0,0.0,1273
4,tipo_orden,str,0.009897,2829,0,0.0,2
5,horas_hombre,float64,0.009897,2829,0,0.0,299
6,num_tecnicos,int64,0.009897,2829,0,0.0,3
7,repuesto_principal,str,0.009897,2829,0,0.0,8
8,costo_repuestos_soles,float64,0.009897,2829,0,0.0,2310

#### A) RESOLUCION MEDIANTE ITERACION PARA  DUPLICADOS USANDO UNA FUNCION REHUTILIZABLE

In [161]:
tablas_mantenimiento = {
    "PN": fact_mtto_PN,
    "PC": fact_mtto_PC,
    "PS": fact_mtto_PS,
}

limpio_mtto = {} #diccionario de dataframes limpios
exactos_mtto = {} #diccionario de dataframes exactos
conflictos_mtto = {} #diccionario de dataframes conflictivos

for planta, df in tablas_mantenimiento.items():
    limpio, exactos, conflictos = resolver_duplicados( #Los 3 outputs del return de la funcion resolver duplicados
        df,
        subset_clave=['orden_id', 'equipo_id','fecha_apertura'], # El evento es el orden_equipo_fecha )la agrupacion de ellos es el evento
        columnas_grano_esperado=['parada_id','tipo_orden'], # Solo puede haber existir de forma unica el contenido del grano
        nombre_tabla=f"Mantenimiento {planta}"
    )

    # Aplicando ordenamiento de las ordenes antes de mostrarlas
    limpio = limpio.sort_values('orden_id')
    exactos = exactos.sort_values('orden_id')
    conflictos = conflictos.sort_values('orden_id')

    # Mostrando resultados por cada planta(usar kEYS no values)
    limpio_mtto[planta] = limpio
    exactos_mtto[planta] = exactos
    conflictos_mtto[planta] = conflictos

[Mantenimiento PN] duplicados exactos: 56 filas | con conflicto real: 0 filas
[Mantenimiento PC] duplicados exactos: 54 filas | con conflicto real: 0 filas
[Mantenimiento PS] duplicados exactos: 46 filas | con conflicto real: 0 filas

#### B) Verificacion manual DE RESOLVER_DUPLICADOS, SI ES CONVENIENTE

In [162]:
# (DESPLEGAR) Proceda a verificar si encontrol conflictos, o busca verificar cuales elementos exactos son los duplicados
#PLANTA NORTE
limpio_mtto['PN']
exactos_mtto['PN']
conflictos_mtto['PN']

#PLANTA SUR


#PLANTA CENTRO

Empty DataFrame
Columns: [orden_id, parada_id, equipo_id, fecha_apertura, tipo_orden, horas_hombre, num_tecnicos, repuesto_principal, costo_repuestos_soles]
Index: []

#### C) VERIFICACION FINAL DE INTEGRIDAD DE DATOS Y CONCATENACION DE DATAFRAMES

In [163]:
# 1) Agregar trazabilidad de planta
for planta, df in limpio_mtto.items(): #Tomamos solo lo limpio que se guardo en un diccionario de dataframes limpios
    df['planta'] = planta #asignar nombre de planta como nueva columna

# 2) Verificación 3/3 completa (duplicados + conflictos en los 3 dataframes)
duplicados_por_planta = {p: df.duplicated().sum() for p, df in limpio_mtto.items()}
conflictos_por_planta = {p: len(df) for p, df in conflictos_mtto.items()}

#Cumple las 2 condiciones para ser TRUE
todo_ok = all(v == 0 for v in duplicados_por_planta.values()) and \
          all(v == 0 for v in conflictos_por_planta.values())

print("Duplicados:", duplicados_por_planta)
print("Conflictos:", conflictos_por_planta)

if todo_ok:
    print("\n,✅ 3/3 plantas limpias y sin conflictos, se procede a concatenar")
    fact_mtto_final = pd.concat(limpio_mtto.values(), ignore_index=True) #pierden su indice original --> un nuevo indice al concatenado
    
    # 3) Chequeo de duplicados cruzados entre plantas
    dup_cruzados = fact_mtto_final.duplicated(subset=['orden_id','equipo_id']).sum() #Se verifica duplicados sobre el concat_df, se suma y se muestra
    print(f"Duplicados cruzados entre plantas: {dup_cruzados}")
    
    print(r'Shape del dataframe',fact_mtto_final.shape,'Mostrando head del dataframe:')
    display(fact_mtto_final.head())
else:
    print("❌ Revisar antes de concatenar")

# 4) Checkpoint final: el conteo por planta debe coincidir con el tamaño de limpio_mtto original
conteo_esperado = {p: len(df) for p, df in limpio_mtto.items()} #diccionario: cantidad del df limpio, en el diccionario de los df limpios
conteo_real = fact_mtto_final['planta'].value_counts().to_dict() # value_counts a las plantas del df concatenado

print('Checkpint de conteo_esperado VS conteo_real:')
print("Esperado:", conteo_esperado)
print("Real:", conteo_real)

assert conteo_esperado == conteo_real, "❌ El conteo no coincide, revisar antes de exportar"
print("✅ Conteo coincide, listo para exportar")

Duplicados: {'PN': np.int64(0), 'PC': np.int64(0), 'PS': np.int64(0)}
Conflictos: {'PN': 0, 'PC': 0, 'PS': 0}

,✅ 3/3 plantas limpias y sin conflictos, se procede a concatenar
Duplicados cruzados entre plantas: 0
Shape del dataframe (7908, 10) Mostrando head del dataframe:

,orden_id,parada_id,equipo_id,fecha_apertura,tipo_orden,horas_hombre,num_tecnicos,repuesto_principal,costo_repuestos_soles,planta
0,OT-000001,PAR-000001,PN-EQ-01,2024-01-09,Correctiva,3.3,1,Rodamiento,6676.0,PN
1,OT-000002,PAR-000002,PN-EQ-01,2024-01-15,Preventiva,4.0,1,Ninguno (solo mano de obra),267.0,PN
2,OT-000003,PAR-000003,PN-EQ-01,2024-01-19,Correctiva,5.2,1,Ninguno (solo mano de obra),4601.0,PN
3,OT-000004,PAR-000004,PN-EQ-01,2024-01-25,Correctiva,13.1,3,Faja/correa,4.0,PN
4,OT-000005,PAR-000006,PN-EQ-01,2024-01-29,Preventiva,7.3,2,Sello mecánico,773.0,PN

Checkpint de conteo_esperado VS conteo_real:
Esperado: {'PN': 2801, 'PC': 2708, 'PS': 2399}
Real: {'PN': 2801, 'PC': 2708, 'PS': 2399}
✅ Conteo coincide, listo para exportar