
  %load_ext autoreload : magic command de Jupyter de autoreload
  
  %autoreload 2 : recarga todo automáticamente(2)

In [1]:
%load_ext autoreload 
%autoreload 2

In [2]:
# PAQUETE LIBRERIAS ANALISIS DE DATOS y de SKLEARN
import pandas as pd
import numpy as np
import seaborn as sea
import matplotlib.pyplot as plt

import sys
sys.path.append('..')

from src.eda import reporte_calidad
from src.eda import detectar_fecha

In [3]:
directory =  r'C:\Users\jbard\Desktop\Library\@CURSOS ACTUALES\@Data Analitycs\Python projects\Mineria-simulacion v2'
fact_mtto_PC= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PC_raw.csv')
fact_mtto_PN= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PN_raw.csv')
fact_mtto_PS= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PS_raw.csv')

In [4]:
from src.eda import reporte_calidad
reporte_calidad(fact_mtto_PC,nombre_df='fact_mtto_PC')

--- Resumen: fact_mtto_PC ---
Total filas: 2735
Filas duplicadas: 27 (0.99%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,repuesto_principal,str,0.009872,2684,51,1.86,7
1,orden_id,str,0.009872,2735,0,0.00,2708
2,parada_id,str,0.009872,2735,0,0.00,2708
3,fecha_apertura,str,0.009872,2735,0,0.00,1271
4,equipo_id,str,0.009872,2735,0,0.00,10
5,tipo_orden,str,0.009872,2735,0,0.00,2
6,horas_hombre,float64,0.009872,2735,0,0.00,306
7,num_tecnicos,int64,0.009872,2735,0,0.00,3
8,costo_repuestos_soles,float64,0.009872,2735,0,0.00,2233

In [6]:
fact_mtto_PC[fact_mtto_PC['repuesto_principal'].isnull()] # Partamos del escenario donde algunos repuestos se perdería el nombre, sin embargo los costos no, por tanto simplemente averiguariamos el nombre del repuesto y reemplazariamos luego. Si existen nulos iría por defecto bajo el nombre 'Indeterminado'

fact_mtto_PC['repuesto_principal']=fact_mtto_PC['repuesto_principal'].fillna('indeterminado')
fact_mtto_PC

,orden_id,parada_id,equipo_id,fecha_apertura,tipo_orden,horas_hombre,num_tecnicos,repuesto_principal,costo_repuestos_soles
0,OT-004314,PAR-005657,PC-EQ-06,2024-05-28,Correctiva,12.7,3,Faja/correa,493.0
1,OT-005483,PAR-007230,PC-EQ-10,2027-08-24,Correctiva,13.1,2,Ninguno (solo mano de obra),4001.0
2,OT-003042,PAR-004020,PC-EQ-01,2027-09-11,Preventiva,9.7,3,Ninguno (solo mano de obra),1002.0
3,OT-005094,PAR-006708,PC-EQ-09,2025-10-03,Correctiva,0.6,2,Ninguno (solo mano de obra),5051.0
4,OT-004318,PAR-005661,PC-EQ-06,2024-06-06,Correctiva,1.0,2,indeterminado,5757.0
...,...,...,...,...,...,...,...,...,...
2730,OT-003349,PAR-004424,PC-EQ-03,2024-03-20,Correctiva,0.9,2,Sello mecánico,7199.0
2731,OT-002985,PAR-003939,PC-EQ-01,2026-11-24,Correctiva,3.7,2,Sensor/instrumento,2870.0
2732,OT-004610,PAR-006038,PC-EQ-07,2025-03-24,Correctiva,8.7,2,Sello mecánico,385.0
2733,OT-003238,PAR-004289,PC-EQ-02,2026-09-06,Correctiva,2.2,2,Motor eléctrico,5208.0
2734,OT-004256,PAR-005590,PC-EQ-05,2027-09-23,Correctiva,7.9,1,Faja/correa,676.0

tipo_fecha
YMD    2735
Name: count, dtype: int64