
  %load_ext autoreload : magic command de Jupyter de autoreload
  
  %autoreload 2 : recarga todo automáticamente(2)

In [175]:
%load_ext autoreload 
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [219]:
# PAQUETE LIBRERIAS ANALISIS DE DATOS y de SKLEARN
import pandas as pd
import numpy as np
import seaborn as sea
import matplotlib.pyplot as plt

import sys
sys.path.append('..')

from src.eda import reporte_calidad
from src.eda import clasificar_formato_fecha
from src.eda import resolver_duplicados

### FACT_MANTENIMIENTO

In [177]:
directory =  r'C:\Users\jbard\Desktop\Library\@CURSOS ACTUALES\@Data Analitycs\Python projects\Mineria-simulacion v2'
fact_mtto_PC= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PC_raw.csv')
fact_mtto_PN= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PN_raw.csv')
fact_mtto_PS= pd.read_csv(directory+r'\data\raw\fact_mantenimiento_PS_raw.csv')

#### 1) FACT_MANTENIMIENTO_PC

1era verificacion de calidad

In [178]:
from src.eda import reporte_calidad
reporte_calidad(fact_mtto_PC,nombre_df='fact_mtto_PC')

--- Resumen: fact_mtto_PC ---
Total filas: 2735
Filas duplicadas: 27 (0.99%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,repuesto_principal,str,0.009872,2684,51,1.86,7
1,orden_id,str,0.009872,2735,0,0.00,2708
2,parada_id,str,0.009872,2735,0,0.00,2708
3,fecha_apertura,str,0.009872,2735,0,0.00,1271
4,equipo_id,str,0.009872,2735,0,0.00,10
5,tipo_orden,str,0.009872,2735,0,0.00,2
6,horas_hombre,float64,0.009872,2735,0,0.00,306
7,num_tecnicos,int64,0.009872,2735,0,0.00,3
8,costo_repuestos_soles,float64,0.009872,2735,0,0.00,2233

VERIFICACION TIPOS DE FECHA QUE HAY EN LA COLUMNA 'FECHA_APERTURA'

In [179]:
tipos_fecha=pd.DataFrame(
    {
        'fecha_apertura': fact_mtto_PC['fecha_apertura'],
        'tipo_fecha': fact_mtto_PC['fecha_apertura'].apply(clasificar_formato_fecha)
    }
)
display(tipos_fecha.head(3))
tipos_de_fecha= tipos_fecha['tipo_fecha'].value_counts()
tipos_de_fecha

#Como no existen mas de otros formatos de fecha, por tanto podemos aplicar directamente la trasnformacion. Hay que tomar en cuenta que quiza haya mas de un formato de fecha en la columna, si ese fuera el caso esto generaria que tengamos hacer tranformacion independiente y un simple pd.to_datetime(df['columna']) no seria suficiente.
#LA SOLUCION sera crear una pipeline para cada escenario o por el contrario hacerlo manualmente para cada tipo_fecha diferente. EN ESTA OCASION EL PIPELINE DE LA VALIDACION DE FECHA YA ESTA REALIZADO DENTRO DE EDA.PY

  fecha_apertura tipo_fecha
0     2024-05-28        YMD
1     2027-08-24        YMD
2     2027-09-11        YMD

tipo_fecha
YMD    2735
Name: count, dtype: int64

In [220]:
validar_fechas(fact_mtto_PC,'fecha_apertura')

Verificación:
     fecha_original tipo_fecha
0        2024-05-28   YMD_TIME
1        2027-08-24   YMD_TIME
2        2027-09-11   YMD_TIME
3        2025-10-03   YMD_TIME
4        2024-06-06   YMD_TIME
...             ...        ...
2730     2024-03-20   YMD_TIME
2731     2026-11-24   YMD_TIME
2732     2025-03-24   YMD_TIME
2733     2026-09-06   YMD_TIME
2734     2027-09-23   YMD_TIME

[2735 rows x 2 columns]

Validación correcta.
Todas las fechas tienen un único formato.
Fecha convertida a datetime.

In [181]:

if fact_mtto_PN['repuesto_principal'].isnull().any():
    fact_mtto_PN['repuesto_principal'] = fact_mtto_PN['repuesto_principal'].fillna('indeterminado')# Partamos del escenario donde algunos repuestos se perdería el nombre, sin embargo los costos no, por tanto simplemente averiguariamos el nombre del repuesto y reemplazariamos luego. Si existen nulos iría por defecto bajo el nombre 'Indeterminado'

    print("Nulos encontrados y reemplazados por 'indeterminado'.")
else:
    print("No se encontraron nulos en 'repuesto_principal', no se aplica transformación.")

Nulos encontrados y reemplazados por 'indeterminado'.

#### 2) FACT_MANTENIMIENTO_PS

In [182]:
from src.eda import reporte_calidad
reporte_calidad(fact_mtto_PS,nombre_df='fact_mtto_PS')

--- Resumen: fact_mtto_PS ---
Total filas: 2422
Filas duplicadas: 23 (0.95%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,repuesto_principal,str,0.009496,2376,46,1.9,7
1,orden_id,str,0.009496,2422,0,0.0,2399
2,parada_id,str,0.009496,2422,0,0.0,2399
3,fecha_apertura,str,0.009496,2422,0,0.0,1204
4,equipo_id,str,0.009496,2422,0,0.0,10
5,tipo_orden,str,0.009496,2422,0,0.0,2
6,horas_hombre,float64,0.009496,2422,0,0.0,277
7,num_tecnicos,int64,0.009496,2422,0,0.0,3
8,costo_repuestos_soles,float64,0.009496,2422,0,0.0,1999

In [183]:

if fact_mtto_PS['repuesto_principal'].isnull().any():
    fact_mtto_PS['repuesto_principal'] = fact_mtto_PS['repuesto_principal'].fillna('indeterminado')# Partamos del escenario donde algunos repuestos se perdería el nombre, sin embargo los costos no, por tanto simplemente averiguariamos el nombre del repuesto y reemplazariamos luego. Si existen nulos iría por defecto bajo el nombre 'Indeterminado'

    print("Nulos encontrados en 'repuesto_principal' y reemplazados por 'indeterminado'.")
else:
    print("No se encontraron nulos en 'repuesto_principal', no se aplica transformación.")

Nulos encontrados en 'repuesto_principal' y reemplazados por 'indeterminado'.

In [184]:
tipos_fecha=pd.DataFrame(
    {
        'fecha_apertura': fact_mtto_PS['fecha_apertura'],
        'tipo_fecha': fact_mtto_PS['fecha_apertura'].apply(clasificar_formato_fecha)
    }
)
display(tipos_fecha.head(3))
tipos_de_fecha= tipos_fecha['tipo_fecha'].value_counts()
tipos_de_fecha

#Como no existen mas de otros formatos de fecha, por tanto podemos aplicar directamente la trasnformacion. Hay que tomar en cuenta que quiza haya mas de un formato de fecha en la columna, si ese fuera el caso esto generaria que tengamos hacer tranformacion independiente y un simple pd.to_datetime(df['columna']) no seria suficiente.
#LA SOLUCION sera crear una pipeline para cada escenario o por el contrario hacerlo manualmente para cada tipo_fecha diferente. EN ESTA OCASION EL PIPELINE DE LA VALIDACION DE FECHA YA ESTA REALIZADO DENTRO DE EDA.PY

  fecha_apertura tipo_fecha
0     2024-10-14        YMD
1     2025-06-24        YMD
2     2024-09-17        YMD

tipo_fecha
YMD    2422
Name: count, dtype: int64

In [185]:
validar_fechas(fact_mtto_PS,'fecha_apertura')

Verificación:
     fecha_original tipo_fecha
0        2024-10-14        YMD
1        2025-06-24        YMD
2        2024-09-17        YMD
3        2024-12-29        YMD
4        2027-01-31        YMD
...             ...        ...
2417     2027-11-15        YMD
2418     2026-08-01        YMD
2419     2026-03-28        YMD
2420     2027-01-30        YMD
2421     2027-06-27        YMD

[2422 rows x 2 columns]

Validación correcta.
Todas las fechas tienen un único formato.
Fecha convertida a datetime.

#### 3) FACT_MANTENIMIENTO_PN

In [190]:
from src.eda import reporte_calidad
reporte_calidad(fact_mtto_PN,nombre_df='fact_mtto_PN')

--- Resumen: fact_mtto_PN ---
Total filas: 2829
Filas duplicadas: 28 (0.99%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,orden_id,str,0.009897,2829,0,0.0,2801
1,parada_id,str,0.009897,2829,0,0.0,2801
2,equipo_id,str,0.009897,2829,0,0.0,10
3,fecha_apertura,datetime64[us],0.009897,2829,0,0.0,1273
4,tipo_orden,str,0.009897,2829,0,0.0,2
5,horas_hombre,float64,0.009897,2829,0,0.0,299
6,num_tecnicos,int64,0.009897,2829,0,0.0,3
7,repuesto_principal,str,0.009897,2829,0,0.0,8
8,costo_repuestos_soles,float64,0.009897,2829,0,0.0,2310

In [251]:
# Descartado 1, no puedo depender de verificar cada una de las tablas si es que se detectaran duplicados, la solucion es diseñar un pipeline que me permita identificar que hacer en caso se detecten duplicados, cuando considerar duplicados y cuando no.... todo manejado dentro de una funcion que pueda reutilizar siempre que se detecten duplicados
fact_mtto_PN[fact_mtto_PN.duplicated()].sort_values('orden_id')

Empty DataFrame
Columns: [orden_id, parada_id, equipo_id, fecha_apertura, tipo_orden, horas_hombre, num_tecnicos, repuesto_principal, costo_repuestos_soles]
Index: []

In [187]:

if fact_mtto_PN['repuesto_principal'].isnull().any():
    fact_mtto_PN['repuesto_principal'] = fact_mtto_PN['repuesto_principal'].fillna('indeterminado')# Partamos del escenario donde algunos repuestos se perdería el nombre, sin embargo los costos no, por tanto simplemente averiguariamos el nombre del repuesto y reemplazariamos luego. Si existen nulos iría por defecto bajo el nombre 'Indeterminado'

    print("Nulos encontrados en 'repuesto_principal' y reemplazados por 'indeterminado'.")
else:
    print("No se encontraron nulos en 'repuesto_principal', no se aplica transformación.")

No se encontraron nulos en 'repuesto_principal', no se aplica transformación.

In [188]:
tipos_fecha=pd.DataFrame(
    {
        'fecha_apertura': fact_mtto_PN['fecha_apertura'],
        'tipo_fecha': fact_mtto_PN['fecha_apertura'].apply(clasificar_formato_fecha)
    }
)
display(tipos_fecha.head(3))
tipos_de_fecha= tipos_fecha['tipo_fecha'].value_counts()
tipos_de_fecha

#Como no existen mas de otros formatos de fecha, por tanto podemos aplicar directamente la trasnformacion. Hay que tomar en cuenta que quiza haya mas de un formato de fecha en la columna, si ese fuera el caso esto generaria que tengamos hacer tranformacion independiente y un simple pd.to_datetime(df['columna']) no seria suficiente.
#LA SOLUCION sera crear una pipeline para cada escenario o por el contrario hacerlo manualmente para cada tipo_fecha diferente. EN ESTA OCASION EL PIPELINE DE LA VALIDACION DE FECHA YA ESTA REALIZADO DENTRO DE EDA.PY

  fecha_apertura tipo_fecha
0     2024-09-23        YMD
1     2026-03-06        YMD
2     2027-09-29        YMD

tipo_fecha
YMD    2829
Name: count, dtype: int64

In [205]:
fact_mtto_PN = fact_mtto_PN_limpio
reporte_calidad(fact_mtto_PN)

--- Resumen: DataFrame ---
Total filas: 2801
Filas duplicadas: 0 (0.00%)
Columnas: 9

,columna,tipo_dato,duplicados,no_nulos,nulos,pct_nulos,unicos
0,orden_id,str,0.0,2801,0,0.0,2801
1,parada_id,str,0.0,2801,0,0.0,2801
2,equipo_id,str,0.0,2801,0,0.0,10
3,fecha_apertura,datetime64[us],0.0,2801,0,0.0,1273
4,tipo_orden,str,0.0,2801,0,0.0,2
5,horas_hombre,float64,0.0,2801,0,0.0,299
6,num_tecnicos,int64,0.0,2801,0,0.0,3
7,repuesto_principal,str,0.0,2801,0,0.0,8
8,costo_repuestos_soles,float64,0.0,2801,0,0.0,2310

#### A) RESOLUCION MEDIANTE ITERACION PARA  DUPLICADOS USANDO UNA FUNCION REHUTILIZABLE

In [249]:
tablas_mantenimiento = {
    "PN": fact_mtto_PN,
    "PC": fact_mtto_PC,
    "PS": fact_mtto_PS,
}

resultados_mtto = {}
exactos_mtto = {}
conflictos_mtto = {}

for planta, df in tablas_mantenimiento.items():
    limpio, exactos, conflictos = resolver_duplicados(
        df,
        subset_clave=['orden_id', 'equipo_id'],
        columnas_grano_esperado=['parada_id', 'fecha_apertura', 'tipo_orden'],
        nombre_tabla=f"Mantenimiento {planta}"
    )
    resultados_mtto[planta] = limpio
    exactos_mtto[planta] = exactos
    conflictos_mtto[planta] = conflictos

[Mantenimiento PN] duplicados exactos: 0 filas | con conflicto real: 0 filas
[Mantenimiento PC] duplicados exactos: 54 filas | con conflicto real: 0 filas
[Mantenimiento PS] duplicados exactos: 46 filas | con conflicto real: 0 filas

In [254]:
exactos.sort_values('orden_id')

,orden_id,parada_id,equipo_id,fecha_apertura,tipo_orden,horas_hombre,num_tecnicos,repuesto_principal,costo_repuestos_soles
227,OT-005556,PAR-007320,PS-EQ-01,2024-09-19,Correctiva,8.4,3,Faja/correa,159.0
1461,OT-005556,PAR-007320,PS-EQ-01,2024-09-19,Correctiva,8.4,3,Faja/correa,159.0
468,OT-005610,PAR-007394,PS-EQ-01,2025-08-02,Correctiva,19.0,1,Sello mecánico,5668.0
1085,OT-005610,PAR-007394,PS-EQ-01,2025-08-02,Correctiva,19.0,1,Sello mecánico,5668.0
1368,OT-005633,PAR-007423,PS-EQ-01,2025-12-16,Correctiva,1.2,1,Sello mecánico,284.0
2080,OT-005633,PAR-007423,PS-EQ-01,2025-12-16,Correctiva,1.2,1,Sello mecánico,284.0
867,OT-005753,PAR-007587,PS-EQ-01,2027-10-07,Preventiva,13.1,2,Sensor/instrumento,429.0
2407,OT-005753,PAR-007587,PS-EQ-01,2027-10-07,Preventiva,13.1,2,Sensor/instrumento,429.0
1775,OT-005948,PAR-007836,PS-EQ-02,2026-07-22,Correctiva,13.0,1,Ninguno (solo mano de obra),708.0
2270,OT-005948,PAR-007836,PS-EQ-02,2026-07-22,Correctiva,13.0,1,Ninguno (solo mano de obra),708.0
1131,OT-005995,PAR-007897,PS-EQ-02,2027-02-19,Preventiva,6.5,1,Revestimiento (liner),1899.0
2085,OT-005995,PAR-007897,PS-EQ-02,2027-02-19,Preventiva,6.5,1,Revestimiento (liner),1899.0
237,OT-006152,PAR-008119,PS-EQ-03,2026-01-19,Preventiva,8.6,1,Motor eléctrico,1900.0
519,OT-006152,PAR-008119,PS-EQ-03,2026-01-19,Preventiva,8.6,1,Motor eléctrico,1900.0
347,OT-006202,PAR-008180,PS-EQ-03,2027-02-24,Preventiva,12.0,2,Ninguno (solo mano de obra),2435.0
762,OT-006202,PAR-008180,PS-EQ-03,2027-02-24,Preventiva,12.0,2,Ninguno (solo mano de obra),2435.0
563,OT-006240,PAR-008238,PS-EQ-03,2027-12-24,Correctiva,3.6,1,Sello mecánico,2237.0
1459,OT-006240,PAR-008238,PS-EQ-03,2027-12-24,Correctiva,3.6,1,Sello mecánico,2237.0
525,OT-006244,PAR-008243,PS-EQ-04,2024-01-21,Preventiva,5.6,3,Ninguno (solo mano de obra),715.0
1764,OT-006244,PAR-008243,PS-EQ-04,2024-01-21,Preventiva,5.6,3,Ninguno (solo mano de obra),715.0
2172,OT-006668,PAR-008786,PS-EQ-05,2026-01-11,Correctiva,4.1,1,Rodamiento,504.0
2232,OT-006668,PAR-008786,PS-EQ-05,2026-01-11,Correctiva,4.1,1,Rodamiento,504.0
76,OT-006774,PAR-008935,PS-EQ-05,2027-07-12,Preventiva,12.3,1,Sello mecánico,870.0
1192,OT-006774,PAR-008935,PS-EQ-05,2027-07-12,Preventiva,12.3,1,Sello mecánico,870.0
971,OT-006874,PAR-009076,PS-EQ-06,2025-02-01,Preventiva,7.3,1,Sensor/instrumento,1808.0
2261,OT-006874,PAR-009076,PS-EQ-06,2025-02-01,Preventiva,7.3,1,Sensor/instrumento,1808.0
999,OT-007031,PAR-009277,PS-EQ-06,2027-05-09,Preventiva,12.0,1,Sensor/instrumento,763.0
2383,OT-007031,PAR-009277,PS-EQ-06,2027-05-09,Preventiva,12.0,1,Sensor/instrumento,763.0
394,OT-007106,PAR-009369,PS-EQ-07,2024-05-22,Correctiva,1.2,1,Sello mecánico,7647.0
1972,OT-007106,PAR-009369,PS-EQ-07,2024-05-22,Correctiva,1.2,1,Sello mecánico,7647.0
226,OT-007142,PAR-009427,PS-EQ-07,2025-05-28,Correctiva,9.9,3,Revestimiento (liner),3660.0
2013,OT-007142,PAR-009427,PS-EQ-07,2025-05-28,Correctiva,9.9,3,Revestimiento (liner),3660.0
312,OT-007313,PAR-009676,PS-EQ-08,2024-09-09,Preventiva,9.3,2,Rodamiento,1257.0
974,OT-007313,PAR-009676,PS-EQ-08,2024-09-09,Preventiva,9.3,2,Rodamiento,1257.0
809,OT-007357,PAR-009734,PS-EQ-08,2025-05-14,Correctiva,4.0,2,Sensor/instrumento,4349.0
1371,OT-007357,PAR-009734,PS-EQ-08,2025-05-14,Correctiva,4.0,2,Sensor/instrumento,4349.0
1624,OT-007458,PAR-009858,PS-EQ-08,2026-08-21,Correctiva,11.1,3,Sello mecánico,3521.0
2413,OT-007458,PAR-009858,PS-EQ-08,2026-08-21,Correctiva,11.1,3,Sello mecánico,3521.0
892,OT-007651,PAR-010141,PS-EQ-09,2026-07-03,Preventiva,4.5,3,Ninguno (solo mano de obra),99.0
2164,OT-007651,PAR-010141,PS-EQ-09,2026-07-03,Preventiva,4.5,3,Ninguno (solo mano de obra),99.0
2285,OT-007676,PAR-010176,PS-EQ-09,2026-12-22,Preventiva,8.0,3,Motor eléctrico,1274.0
2400,OT-007676,PAR-010176,PS-EQ-09,2026-12-22,Preventiva,8.0,3,Motor eléctrico,1274.0
695,OT-007822,PAR-010396,PS-EQ-10,2026-04-03,Preventiva,6.6,1,Motor eléctrico,1193.0
2200,OT-007822,PAR-010396,PS-EQ-10,2026-04-03,Preventiva,6.6,1,Motor eléctrico,1193.0
397,OT-007829,PAR-010407,PS-EQ-10,2026-05-31,Correctiva,3.2,3,Ninguno (solo mano de obra),672.0
2143,OT-007829,PAR-010407,PS-EQ-10,2026-05-31,Correctiva,3.2,3,Ninguno (solo mano de obra),672.0